# -*- coding: utf-8 -*-
"""sqroot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WMrkdeAWveTBVWcDKAs63X-wyReIXlWx
"""

def sqroot (x):
  return x**(0.5)

